name: 'Override data'

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm
    - name: Install
      run: npm ci
    - name: Run script
      run: node override.js
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
